### ISSUE TITLE
constructor for rosbridge_suite objects

### ISSUE THREAD

**Issue by MohMaz** [ros/genpy#118]
I think it'll be useful to add constructors which can instantiate the python object from a `json` object.
When we work with `rosbridge_suite` we lose the byte array.

**Comment by dirk-thomas** [comment]
It should be straight forward to write a generic function which takes a json object and a message class/ instance and populate all members. So there is no need to generate any additional code imo.

**Comment by dirk-thomas** [comment]
Assuming the previous response answered the question I will close this ticket.
