### ISSUE TITLE
genpy.Time comparison problem in Python 3 (Melodic)

### ISSUE THREAD

**Issue by jkua** [ros/genpy#119]
With Melodic and Python3 (and Python 2 with newer versions of Numpy), I'm having problems with `genpy.Time` instances initialized from `(sec, nano)` values which are of type `numpy.int64`. Comparisons (<, >, <=, >=) fail with a `TypeError` except for ==. 

This works fine in Python 2 and older versions (1.13.3 tested) of Numpy. However, newer versions (1.16.6 tested) fail with a different `TypeError` that states a deprecation of boolean subtraction in numpy. 

Also, initializing with a `numpy.float64` works just fine. 

Same issue with `rospy.Time`.

Code:
```python
import numpy as np
import genpy 

a = np.array([1583968688, 8586883])
print('Type of a[0]: {}'.format(type(a[0])))

# Fails in Python 3 with np.int64 type
t = genpy.Time(a[0], a[1])
print('\nt: {}'.format(t))
print('Compare t < t: {}'.format(t < t))

# Works in Python 3 with regular int type
t2 = genpy.Time(int(a[0]), int(a[1]))
print('\nt2: {}'.format(t2))
print('Compare t2 < t2: {}'.format(t2 < t2))
```

Python 3.6.9 / numpy 1.18.1:
```
Type of a[0]: <class 'numpy.int64'>

t: 1583968688008586883
Traceback (most recent call last):
  File "rosTimeProblem.py", line 9, in <module>
    print('Compare t < t: {}'.format(t < t))
TypeError: '<' not supported between instances of 'Time' and 'Time'
```

Python 2.7.17 / numpy 1.13.3:
```
Type of a[0]: <type 'numpy.int64'>

t: 1583968688008586883
Compare t < t: False

t2: 1583968688008586883
Compare t2 < t2: False
```

Python 2.7.17 / numpy 1.16.6:
```
Type of a[0]: <type 'numpy.int64'>

t: 1583968688008586883
Traceback (most recent call last):
  File "rosTimeTest.py", line 10, in <module>
    print('Compare t < t: {}'.format(t < t))
  File "/opt/ros/melodic/lib/python2.7/dist-packages/genpy/rostime.py", line 270, in __cmp__
    return (a > b) - (a < b)
TypeError: numpy boolean subtract, the `-` operator, is deprecated, use the bitwise_xor, the `^` operator, or the logical_xor function instead.
```

**Comment by dirk-thomas** [comment]
Populating `genpy.Time` with `numpy` value types is certainly not a currently supported use case so I am not surprised. Please consider to contribute a pull request if you would like this to become supported.
