### ISSUE TITLE
release 0.6.10 into melodic

### ISSUE THREAD

**Issue by flixr** [ros/genpy#120]
Please release 0.6.10 into melodic as well.

This is needed in the official melodic distro, because all message packages need to regenerate the serialization code with this genpy version (to get fixes for reproducibility and correct exception messages).

**Comment by dirk-thomas** [comment]
Since those changes (#110, #111, #113) are not critical to deploy it only makes sense to release this package into Melodic when other ROS core releases happen (since it causes the entire distro to be rebuild). I will do the bloom release now but it might be a while before this becomes available.
