### ISSUE TITLE
rospy absolute duration bug

### ISSUE THREAD

**Issue by j-bv** [ros/genpy#35]
Hello,
I use ROS hydro and I think I found an error in the code of the rospy.Duration class

When I do : 

> print abs(rospy.Duration.from_sec(0.5))

it prints -500000000 instead of 500000000. That's because the code only takes into account the number of seconds. 
cf : https://github.com/ros/genpy/blob/indigo-devel/src/genpy/rostime.py

```
    def __abs__(self):
        """
        Absolute value of this duration
        :returns: positive :class:`Duration`
        """
        if self.secs > 0:
            return self
        return self.__neg__()
```

It should be :

```
    def __abs__(self):
        """
        Absolute value of this duration
        :returns: positive :class:`Duration`
        """
        if self.secs < 0 or (self.secs == 0 and self.nsecs<0):
            return self.__neg__()
        return self
```

**Comment by dirk-thomas** [comment]
Thank you for reporting the problem. That is indeed wrong. Please see PR #36 for the proposed fix.

Since the `secs` and `nsecs` value are being normalized using the `_canon` function I think the condition must only be changed to:

    if self.secs >= 0:
