### ISSUE TITLE
Duration.__floordiv__(Duration, int) is ill-defined

### ISSUE THREAD

**Issue by eric-wieser** [ros/genpy#49]
Floor division makes no sense, because floor makes no sense for duration, as it requires some sense of a base unit.

Two possible sets of semantics could be:

* `Duration // int = Duration.from_nsecs(d.to_nsecs() // int)`
* `Duration // int = Duration.from_secs(d.to_secs() // int)`

Unfortunately, the current semantics are neither of these!

**Comment by dirk-thomas** [comment]
That is a good point. I would suggest to:
* return `NotImplemented` for `__floordiv__`
* change `__div__` to be the same as `__truediv__`

Not sure if this should go into Kinetic only or also into Indigo / Jade. While it is a change I can't imagine anyone relying on this weird behavior. @ros/ros_team any comments?

**Comment by wjwwood** [comment]
Definitely +1 for Kinetic with a migration note.

For Indigo/Jade, I think it is somewhat likely someone has run into this and knowingly or unknowingly worked around this issue. I also think it would be a nasty thing to catch as it will almost certainly not result in an obvious error but rather a logic change in behavior. So I'm -0 for releasing this change into Indigo and Jade.

**Comment by eric-wieser** [comment]
I've just realized that my second implementation choice, `Duration.from_nsecs(d.to_nsecs() // int)`, is exactly the same as `__truediv__`, since nsecs are ultimately rounded anyway

**Comment by eric-wieser** [comment]
The current behavior is extremely broken, so I'd be in favor of at the very least changing `__div__` to match `__truediv__`, and adding a deprecation warning to `__floordiv__`

```python
> (Duration(3.2) // 2).to_secs()
1.1
```

**Comment by eric-wieser** [comment]
More alarmingly, at some point someone decided that this was [intended behaviour](https://github.com/ros/genpy/blob/indigo-devel/test/test_genpy_rostime_truediv.py#L59)

**Comment by dirk-thomas** [comment]
I thought about this some more and came up with #58 which contains a rational why I went for only adding a warnings for this.
