### ISSUE TITLE
Fixed size custom message list - All entries have reference to same object

### ISSUE THREAD

**Issue by reinzor** [ros/genpy#76]
CustomMsgEntry.msg

    float32 foo
    float32 bar

CustomMsgEntryList.msg

    CustomMsgEntry[50] list

When using this in python:

    entry_list = CustomMsgEntryList()
    entry_list[0].foo = 2
    print entry_list

You will see that 2 is assigned to `foo` of all objects in the list. You could just instantiate a new `CustomEntry` object and assign this as a work around.

**Comment by dirk-thomas** [comment]
This should already be addressed by #74. Please make sure that you are using the latest release.
