### ISSUE TITLE
Error: the - operator, is deprecated (rostime)

### ISSUE THREAD

**Issue by diasdm** [ros/genpy#93]
Hi everyone,
Not sure if this is a bug or if I am doing something wrong.
I was using the rosbag api to save a bag (`output_bag.write(topic, msg, t)`) when I came across this error:
`Traceback (most recent call last):
 (...)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rosbag/bag.py", line 382, in write
    if t > self._curr_chunk_info.end_time:
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/genpy/rostime.py", line 270, in __cmp__
    return (a > b) - (a < b)
TypeError: numpy boolean subtract, the `-` operator, is deprecated, use the bitwise_xor, the `^` operator, or the logical_xor function instead.
`
I ended up editing this [line](https://github.com/ros/genpy/blob/kinetic-devel/src/genpy/rostime.py#L270) in my rostime.py file. Just replaced the `-` by a `^` and it worked.
Thank you.

**Comment by dirk-thomas** [comment]
> (a > b) - (a < b)

This equation return a numeric value `1`, `0`, or `-1`. The operator `^` you suggested results in a boolean which is not the same and therefore that is not a valid replacement.

I am not aware of the operator `-` being "deprecated" for boolean values (which is what it is being used for in that line). I am not sure how you got a numpy boolean substract there. Please provide a reproducible example for the `TypeError`.
